on:
    workflow_call:
      inputs:
        testvar:
          required: true
          type: string

jobs:

    configuremvn:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: mvn version
            run: mvn --version
          - name: get files
            run: |
              pwd
              cd ..
              pwd
              ls -R
              cd TestingSharedPipelines
          - name: mvn install package
            run: mvn clean package install --settings '.\muleapp\.settings\settings.xml' -DattachMuleSources -nsu -DskipMunitTests
