on:
    workflow_call:
      inputs:
        testvar:
          required: true
          type: string

jobs:
    print-context:
        runs-on: ubuntu-latest
        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}
            run: echo "$GITHUB_CONTEXT"